version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "1234:3090"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "4321:27017"
